# Generated by Django 5.1.5 on 2026-07-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
