# Generated by Django 5.1.5 on 2026-07-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_alerts', '0002_pricealert_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='triggered_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
