# Generated by Django 5.1.5 on 2026-07-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('transports', '0003_alter_searchhistory_transport_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='transports.transport'),
        ),
    ]
