# Generated by Django 5.1.5 on 2026-07-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('price_alert', 'Price Alert'), ('route_match', 'Route Match'), ('subscription', 'Subscription'), ('ai', 'AI'), ('system', 'System'), ('ticket', 'Ticket'), ('chat', 'Chat')], default='system', max_length=30),
        ),
    ]
