# Generated by Django 5.1.5 on 2026-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_options_ticket_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_sequence',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
