# Generated by Django 5.1.5 on 2026-08-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='limits',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
