# Generated by Django 5.1.5 on 2026-06-29 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_is_active'),
        ('transports', '0002_searchhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='transport_type',
            field=models.CharField(choices=[('all', 'All'), ('air', 'Air'), ('sea', 'Sea')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.UniqueConstraint(fields=('company', 'transport_type', 'source', 'destination', 'departure_date'), name='unique_transport_route'),
        ),
    ]
