# Generated by Django 5.1.5 on 2026-08-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_alter_searchhistory_transport_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='price_unit',
            field=models.CharField(choices=[('shipment', 'Per Shipment'), ('kg', 'Per KG'), ('cbm', 'Per CBM'), ('pallet', 'Per Pallet'), ('container', 'Per Container')], default='shipment', max_length=20),
        ),
    ]
