# Generated by Django 5.1.5 on 2026-06-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('busy', 'Busy'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
    ]
