# Generated by Django 5.1.5 on 2026-08-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_online'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_online',
            new_name='manual_status',
        ),
    ]
